repos:
  - repo: .
    rev: 1.5.3
    hooks:
      - id: duolingo
  - repo: local
    hooks:
      - id: test
        name: Tests
        entry: make test
        language: system
        always_run: true
